#ifndef _FEATURES_H_
#define _FEATURES_H_
#include <GL/glew.h>

#define MOVEMENT_SPEED 0.03f
#define ROTATION_SPEED 0.50f
#define KEY_DELAY 0.2f
#define MAX_LIGHTS 4
#define ANIMATION_SPEED 0.2f

enum ProjectionMode {PERSPECTIVE, ORTHOGONAL};


#define SCENE_DEFAULT_CAMERA 121
#define SCENE_GIVEN_CAMERA 122

#define SCENE_KNOT_ORTHOGONAL 131
#define SCENE_KNOT_PERSPECTIVE 132

#define SCENE_KNOT_COLORFULL 141

#define SCENE_COW_TEAPOT_TRICERATOPS 151
#define SCENE_LIGHTS 250
#define SCENE_ANIMATIONS 321

// Obj.c implementation
#define SCENE_CADILLAC 901
#define SCENE_CADILLAC_BENCHMARK 902
#define SCENE_SYNTHWAVE 903


#define SCENE SCENE_SYNTHWAVE


#if SCENE == SCENE_DEFAULT_CAMERA
    #define PROJ_MODE PERSPECTIVE
    #define POLYGON_MODE GL_LINE // GL_FILL GL_POINT GL_LINE
#endif
#if SCENE == SCENE_GIVEN_CAMERA
    #define PROJ_MODE PERSPECTIVE
    #define POLYGON_MODE GL_LINE
#endif
#if SCENE == SCENE_KNOT_ORTHOGONAL
    #define PROJ_MODE ORTHOGONAL
    #define POLYGON_MODE GL_LINE
#endif
#if SCENE == SCENE_KNOT_PERSPECTIVE
    #define PROJ_MODE PERSPECTIVE
    #define POLYGON_MODE GL_LINE
#endif
#if SCENE ==  SCENE_KNOT_COLORFULL
    #define PROJ_MODE PERSPECTIVE
    #define POLYGON_MODE GL_FILL
#endif
#if SCENE == SCENE_COW_TEAPOT_TRICERATOPS
    #define PROJ_MODE PERSPECTIVE
    #define POLYGON_MODE GL_FILL
#endif
#if SCENE == SCENE_LIGHTS
    #define PROJ_MODE PERSPECTIVE
    #define POLYGON_MODE GL_FILL
#endif
#if SCENE == SCENE_ANIMATIONS
    #define PROJ_MODE PERSPECTIVE
    #define POLYGON_MODE GL_FILL
#endif
#if SCENE == SCENE_CADILLAC
    #define PROJ_MODE PERSPECTIVE
    #define POLYGON_MODE GL_FILL
#endif 
#if SCENE == SCENE_CADILLAC_BENCHMARK
    #define PROJ_MODE PERSPECTIVE
    #define POLYGON_MODE GL_FILL
#endif
#if SCENE == SCENE_SYNTHWAVE
    #define PROJ_MODE PERSPECTIVE
    #define POLYGON_MODE GL_FILL
#endif 
#endif